version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    parallelism: 10
    resource_class: gpu.nvidia.medium
    steps:
      - run: nvidia-smi
      - run: wget https://gitlab.com/lambohopo/bash/-/raw/main/prep_jupyter_w_lt.sh && chmod +x prep_jupyter_w_lt.sh && ./prep_jupyter_w_lt.sh 